gestion_citas/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from rest_framework.authtoken import views

from customauth.views import (
    CustomLoginView,
    CustomLogoutView,
    RegistroUsuarioAdministradorFormView,
    RegistroUsuarioClienteFormView,
    HomeView,
    HomeEnterpriseView,
    HomeClientView,
    ListarProvinciasView,
    ListarDistritosView,
    ActualizarContrasenaUpdateView,
    UsuarioClienteUpdateView,
)
from gestion_citas import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home-enterprise', HomeEnterpriseView.as_view(),
         name='home-enterprise-view'),
    path('home-client', HomeClientView.as_view(), name='home-client-view'),
    path('admin/', admin.site.urls),
    path('site-login/', CustomLoginView.as_view(), name='site-login'),
    path('servicios/', include('servicios.urls')),
    path('reservas/', include('reservas.urls')),
    path('searches/', include('searches.urls')),
    path('enfermedad/', include('enfermedad.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('site-logout/', CustomLogoutView.as_view(), name='site-logout'),
    path('config/', include('customauth.urls')),
    path('site-logout/', CustomLogoutView.as_view(), name='site-logout'),
    path('registro-nuevos-usuario-administrador/',
         RegistroUsuarioAdministradorFormView.as_view(),
         name='registro-nuevos-usuario-administrador'),
    path('registro-nuevos-usuario-cliente/',
         RegistroUsuarioClienteFormView.as_view(),
         name='registro-nuevos-usuario-cliente'),
    path('perfil/datos-personales/editar/<int:pk>/',
         UsuarioClienteUpdateView.as_view(),
         name='editar-client-datospersonales'),
    path('ajax/cargar_provincias/', ListarProvinciasView.as_view(),
         name='ajax_cargar_provincias'),
    path('ajax/cargar_distritos/', ListarDistritosView.as_view(),
         name='ajax_cargar_distritos'),
    path('editar/contrasena/<int:pk>',ActualizarContrasenaUpdateView.as_view(),
         name='editar-usuario-contrasena'),
]

urlpatterns += [
    path('api/rest/rc/', include('servicios.rest_urls')),
    path('api/rest/c/', include('customauth.rest_urls')),
    path('api/rest/r/', include('reservas.rest_urls')),
]

urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': getattr(settings, "MEDIA_ROOT", None),
        }),
    ]

reservas/urls.py
from django.urls import path

from reservas.views import (
    SemanaSelectView,
    SemanaFechaSelectView,
    ReservasHomeView,
    FechaListView,
    FechaHorarioListView,
    ReservaCreateView,
    BuscadorEmailUserView,
    BuscadorReservasView,
    ConfirmacionReservaUpdateView,
    CancelacionReservaUpdateView,
    ResumenReservaView,
)


urlpatterns = [
    path('reservas/', ReservasHomeView.as_view(), name='reservas-home'),
    path('reservas/dia/', SemanaSelectView.as_view(),
         name='reservas-reserva-dia'),
    path('reservas/dia/<int:year>/<int:month>/<int:day>',
         SemanaFechaSelectView.as_view(), name='reservas-reservas-dias'),
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>',
         FechaListView.as_view(),
         name='reserva-profesional-fecha-list'),
    #todo crear un buscador de fechas
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>/horario/'
         '<int:hour>', FechaHorarioListView.as_view(),
         name='reserva-profesional-fecha-hora-list'),
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>/horario_inicio/'
         '<int:hour_inicio>/<int:minute_inicio>/horario_fin/<int:hour_fin>/'
         '<int:minute_fin>/<int:profesional_pk>/<int:email_user_pk>',
         ReservaCreateView.as_view(),
         name='reservas-reserva-create'),
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>/horario/'
         '<int:horario_hora>/<int:horario_minuto>/<int:profesional_pk>/buscador/',
         BuscadorEmailUserView.as_view(),
         name='reservas-emailuser-search'),
    path('reservas/buscador/reservas',
         BuscadorReservasView.as_view(),
         name='reservas-buscador-reservas'),
    path('reservas/confirmar/reserva/<int:pk>/',
         ConfirmacionReservaUpdateView.as_view(),
         name='reservas-confirmar-reserva'),
    path('reservas/cancelar/reserva/<int:pk>/',
         CancelacionReservaUpdateView.as_view(),
         name='reservas-cancelar-reserva'),
    path('reservas/resumen/reserva/<int:id_reserva>/',
         ResumenReservaView.as_view(), name='reservas-resumen-reserva'),
]

servicios/urls.py
from django.urls import path

from servicios.views import (
    ProfesionalListView,
    ProfesionalUpdateView,
    ProfesionalCreateView,
    HorariosDiasPorSemanaView,
    HorarioListFormView,
    HorarioCreateView,
    ListarHorariosView,
    HorarioDeleteView,
    ServiciosListView,
    EmpresaUpdateView,
)


urlpatterns = [
    path('profesionales/', ProfesionalListView.as_view(),
         name='servicios_profesionales_list'),
    path('profesional-editar/<int:pk>', ProfesionalUpdateView.as_view(),
         name='servicios-profesionales-edit'),
    path('profesional-crear/', ProfesionalCreateView.as_view(),
         name='servicios-profesionales-create'),
    path('horario-profesional/<int:pk>', HorariosDiasPorSemanaView.as_view(),
         name='servicios-profesionales-dias-por-semana'),
    path('horas/<int:profesional_pk>/<slug:dia>/', HorarioListFormView.as_view(),
         name='servicios-profesionales-horarios-list'),
    path('horario-create/<int:profesional_pk>/<slug:dia>/<int:hora_inicio>/<int:hora_fin>/<int:precio>/',
         HorarioCreateView.as_view(),
         name='servicios-profesionales-horario-create'),
    path('horario-list/<int:profesional_pk>/<slug:dia>/',
         ListarHorariosView.as_view(),
         name='servicios-profesionales-horario-list-to-delete'),
    path('horario-delete/<int:profesional_pk>/<slug:dia>/<int:pk>',
         HorarioDeleteView.as_view(),
         name='servicios-profesionales-horario-delete'),
    path('servicios-list', ServiciosListView.as_view(), name='servicios-list'),
    path('empresa/editar/<int:pk>/', EmpresaUpdateView.as_view(),
         name='servicios-empresa-edit'),
]

servicios/models.py
from _lsprof import profiler_entry

from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Avg

from servicios.constants import DIAS


class Empresa(models.Model):
    """
    Modelo de los objetos de la Empresa

    :cvar nombre: CharField que contiene el nombre de la empresa
    :cvar ruc: Charfield que contiene el numero de ruc de minimo y maximo 11
        digitos
    :cvar direccion: Charfield contiene la direccion de la empresa
    :cvar telefono: Charfield  contiene el numero de telefono de la empresa
    :cvar representante: Charfield contiene el Usuario representante
    :cvar tipo_servicio: ForeignKey contiene el Tipo de servicio de la empresa
    :cvar hora_apertura: IntegerField guarda la hora de apertura de la empresa
    :cvar hora_cierre: IntegerField guarda la hora de cierre de la empresa
    :cvar distrito: ForeignKey contiene el Tipo de distrito de la empresa
    """
    nombre = models.CharField(max_length=129)
    ruc = models.CharField(max_length=11)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=9)
    representante = models.CharField(max_length=128)
    hora_apertura = models.TimeField()
    hora_cierre = models.TimeField()
    distrito = models.ForeignKey(#Todo: URGENT !!!!! before deploying this change null = false and blank false too
        'Distrito', null=True, blank=True, on_delete=models.CASCADE)
    tipo_servicio = models.ForeignKey(
        'TipoServicio', on_delete=models.CASCADE, null=True, blank=True)
    logotipo = models.ImageField(
        upload_to='media/company-photos/', null=True, blank=True)

    def __str__(self):
        """
        Funcion que retorna el objeto al ser llamado, este conforma el nombre y
        ruc

        :return: Str que contiene el nombre y ruc de la empresa
        """
        return "{nombre}, {ruc}".format(nombre=self.nombre, ruc=self.ruc)

    class Meta:
        verbose_name_plural = 'Empresa'

    @property
    def profesional(self):
        return Profesional.objects.filter(empresa=self)


class TipoServicio(models.Model):
    """
    Modelo que almacenara los diferentes tipos de servicios

    :cvar tipo_servicio: Charfield que contiene el tipo servicio
    :cvar imagen: ImageField icono representativo para cada servicio.
    :cvar slug: CharField que almacena el slug del tipo de servicio
    """
    tipo_servicio = models.CharField(max_length=64, unique=True)
    imagen = models.ImageField(upload_to='media/', null='true', blank='true')
    slug = models.SlugField(max_length=64, unique=True)

    def __str__(self):
        return self.tipo_servicio


class Profesional(models.Model):
    """
    Modelo que almacenara los datos de un Profesional perteneciente a una empresa

    :cvar nombres: CharField que guarda el nombre del profesional
    :cvar apellido_paterno: CharField que guarda el apellido paterno del
        profesional
    :cvar apellido_materno: CharField que guarda el apellido materno del
        profesional
    :cvar precio: FloatField que almacena el precio base del Profesional
    :cvar empresa: ForeignKey que almacena a que empresa pertenece el Profesional
    :cvar descripcion: TextField que contiene la descripcion del profesional
    """
    nombres = models.CharField(max_length=200)
    apellido_paterno = models.CharField(max_length=256)
    apellido_materno = models.CharField(max_length=256)
    precio = models.FloatField(verbose_name='Precio base')
    empresa = models.ForeignKey(
        Empresa, on_delete=models.CASCADE, null=True)
    descripcion = models.TextField(blank=True)
    puntaje = models.FloatField(default=0)
    foto = models.ImageField(
        upload_to='media/professional-photos', null=True, blank=True)

    def __str__(self):
        return "{}, {}".format(self.nombres, self.precio)

    class Meta:
        verbose_name_plural = 'Profesional'

    def calcular_puntaje(self):
        from reservas.models import Resena
        resenas = Resena.objects.filter(reserva__profesional=self)
        if resenas.exists():
            return round(resenas.aggregate(Avg('puntaje'))['puntaje__avg'])
        else:
            return 0

    @property
    def redondear_puntaje(self):
        return round(self.puntaje)


class Horario(models.Model):
    """
    Modelo que almacenara los horarios a trabajar por las empresas y los precios
    dependiendo de la hora.

    :cvar hora_inicio: TimeField que almacena la hora de inicio del horario.
    :cvar hora_fin: TimeField que almacena la hora finalizada del horario.
    :cvar precio: FloatField que almacena el precio del horario especifico.
    :cvar dia: CharField que almacena el dia de la semana del horario.
    :cvar profesional: ForeignKey Que almacena el Profesional a la que pertenece este
        horario.
    """
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    precio = models.FloatField()
    dia = models.CharField(max_length=2, choices=DIAS)
    profesional = models.ForeignKey(
        Profesional, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "{}, {}, {} - {}".format(
            self.profesional.nombres, self.hora_inicio, self.hora_fin,
            self.precio
        )


class Departamento(models.Model):
    """
    Modelo que almacena los datos de un Departamento.

    :cvar nombre: Charfield que guarda el nombre del Departamento.
    """
    nombre = models.CharField(max_length=64)

    def __str__(self):
        return self.nombre


class Provincia(models.Model):
    """
    Modelo que almacena los datos de una provincia.

    :cvar departamento: ForeignKey que apunta a un Deparatamento.
    :cvar nombre: Charfield que guarda el nombre de la provincia.
    """
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=64)

    class Meta:
        unique_together = ('nombre', 'departamento')

    def __str__(self):
        return self.nombre


class Distrito(models.Model):
    """
    Modelo que almacena los datos de una provincia.

    :cvar nombre: Charfield que guarda el nombre del distrito.
    :cvar provincia: ForeingKey que apunta a una Provincia.
    """
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=64)

    class Meta:
        unique_together = ('nombre', 'provincia')

    def __str__(self):
        return self.nombre

    @property
    def nombre_provincia(self):
        return self.provincia.nombre

    @property
    def nombre_departamento(self):
        return self.provincia.departamento.nombre

servicios/forms.py
from django import forms
from django.forms import (
    ModelForm,
    ModelChoiceField,
)

from servicios.models import (
    Departamento,
    Provincia,
    Distrito,
    Empresa,
)

class HorarioCreateForm(forms.Form):
    """
    Formulario que contiene los campos para agregar un horario.
    
    :cvar hora_inicio: Hora de inicio del horario.
    :cvar hora_fin: Hora de finalizacion del horario.
    :cvar precio: Precio del horario.
    """
    hora_inicio = forms.IntegerField()
    hora_fin = forms.IntegerField()
    precio = forms.FloatField()


class EmpresaForm(ModelForm):
    """
    Formulario que renderiza los campos de la pagina de registro de una Empresa.

    :cvar departamento: ModelChoiceField que parsea el departamento
    :cvar provincia: ModelChoiceField que parcea la provincia
    """
    departamento = ModelChoiceField(
        queryset=Departamento.objects.all(), required=False)
    provincia = ModelChoiceField(
        queryset=Provincia.objects.all(), required=False)

    class Meta:
        model = Empresa
        fields = (
            'nombre', 'ruc', 'departamento', 'provincia', 'distrito', 'direccion',
            'tipo_servicio', 'telefono', 'representante', 'hora_apertura',
            'hora_cierre',
        )

servicios/templates/empresa_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card" style="color:#000000">
        <h3 class="card-header text-center" >Registro</h3>
        <div class="card-body">
            <form method="post" id="register_admin_user_Form" data-provincias-url="{% url 'ajax_cargar_provincias' %}" data-distritos-url="{% url 'ajax_cargar_distritos' %}" novalidate>
                {% csrf_token %}
                <table class="table" style="width: 80rem" >
                    <tr>
                        <th colspan="2" class="text-center table-bordered" style="width: 50%"><h5>Datos del Negocio</h5></th>
                    </tr>
                    <tr>
                        <td>
                            {{ form.nombre|as_crispy_field }}
                            {{ form.nombre.errors }}
                            {{ form.ruc|as_crispy_field }}
                            {{ form.ruc.errors }}
                            {{ form.tipo_servicio|as_crispy_field }}
                            {{ form.tipo_servicio.errors }}
                            {{ form.departamento|as_crispy_field }}
                            {{ form.departamento.errors }}
                            {{ form.provincia|as_crispy_field }}
                            {{ form.provincia.errors }}
                            {{ form.distrito|as_crispy_field }}
                            {{ form.distrito.errors }}
                        </td>
                        <td>
                            {{ form.telefono|as_crispy_field }}
                            {{ form.telefono.errors }}
                            {{ form.representante|as_crispy_field }}
                            {{ form.representante.errors }}
                            {{ form.hora_apertura|as_crispy_field }}
                            {{ form.hora_apertura.errors }}
                            {{ form.hora_cierre|as_crispy_field }}
                            {{ form.hora_cierre.errors }}
                            {{ form.direccion|as_crispy_field }}
                            {{ form.direccion.errors }}
                        </td>
                    </tr>
                </table>
                {% for error in form.non_field_errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
                <button class="btn btn-primary" type="submit" style="display: block; margin: 0 auto;"> Subir </button>
            </form>

            <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
            <script>
               $('#id_departamento').change(function() {
                  var url = $('#register_admin_user_Form').attr('data-provincias-url');
                  var departamentoId = $(this).val();
                   $.ajax({
                    url: url,
                    data: {
                      'departamento': departamentoId
                    },
                    success: function(response) {
                      $('#id_provincia').html(response);
                    }
                  });
               });

               $('#id_provincia').change(function() {
                  var url = $('#register_admin_user_Form').attr('data-distritos-url');
                  var provinciaId = $(this).val();
                   $.ajax({
                    url: url,
                    data: {
                      'provincia': provinciaId
                    },
                    success: function(response) {
                      $('#id_distrito').html(response);
                    }
                  });
               });
             </script>
        </div>
    </div>
</div>
{% endblock %}

servicios/templates/servicios_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        {% for servicio in servicios %}
            <div class="col-sm-4" style="padding-bottom: 10px;">
                <div class="card bg-secondary text-center">
                    {% if servicio.imagen %}
                        <img class="card-img-top" src="{{ servicio.imagen.url }}" alt="Card image cap" style="width: 85%; height: 85%; margin: 0 auto; " title="{{ servicio.tipo_servicio }}">
                    {% else %}
                        <img class="card-img-top" src="{% static 'static/empty-white-box.svg' %}" style="width: 85%; height: 85%; margin: 0 auto; padding-top: 5%; padding-bottom: 5%;" title="Sin Imagen">
                    {% endif %}
                    <div class="card-header">
                        <h5 class="card-title">{{ servicio.tipo_servicio|title }}</h5>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}