gestion_citas/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from rest_framework.authtoken import views

from customauth.views import (
    CustomLoginView,
    CustomLogoutView,
    RegistroUsuarioAdministradorFormView,
    RegistroUsuarioClienteFormView,
    HomeView,
    HomeEnterpriseView,
    HomeClientView,
    ListarProvinciasView,
    ListarDistritosView,
    ActualizarContrasenaUpdateView,
    UsuarioClienteUpdateView,
)
from gestion_citas import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home-enterprise', HomeEnterpriseView.as_view(),
         name='home-enterprise-view'),
    path('home-client', HomeClientView.as_view(), name='home-client-view'),
    path('admin/', admin.site.urls),
    path('site-login/', CustomLoginView.as_view(), name='site-login'),
    path('servicios/', include('servicios.urls')),
    path('reservas/', include('reservas.urls')),
    path('searches/', include('searches.urls')),
    path('enfermedad/', include('enfermedad.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('site-logout/', CustomLogoutView.as_view(), name='site-logout'),
    path('config/', include('customauth.urls')),
    path('site-logout/', CustomLogoutView.as_view(), name='site-logout'),
    path('registro-nuevos-usuario-administrador/',
         RegistroUsuarioAdministradorFormView.as_view(),
         name='registro-nuevos-usuario-administrador'),
    path('registro-nuevos-usuario-cliente/',
         RegistroUsuarioClienteFormView.as_view(),
         name='registro-nuevos-usuario-cliente'),
    path('perfil/datos-personales/editar/<int:pk>/',
         UsuarioClienteUpdateView.as_view(),
         name='editar-client-datospersonales'),
    path('ajax/cargar_provincias/', ListarProvinciasView.as_view(),
         name='ajax_cargar_provincias'),
    path('ajax/cargar_distritos/', ListarDistritosView.as_view(),
         name='ajax_cargar_distritos'),
    path('editar/contrasena/<int:pk>',ActualizarContrasenaUpdateView.as_view(),
         name='editar-usuario-contrasena'),
]

urlpatterns += [
    path('api/rest/rc/', include('servicios.rest_urls')),
    path('api/rest/c/', include('customauth.rest_urls')),
    path('api/rest/r/', include('reservas.rest_urls')),
]

urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': getattr(settings, "MEDIA_ROOT", None),
        }),
    ]

reservas/urls.py
from django.urls import path

from reservas.views import (
    SemanaSelectView,
    SemanaFechaSelectView,
    ReservasHomeView,
    FechaListView,
    FechaHorarioListView,
    ReservaCreateView,
    BuscadorEmailUserView,
    BuscadorReservasView,
    ConfirmacionReservaUpdateView,
    CancelacionReservaUpdateView,
    ResumenReservaView,
)


urlpatterns = [
    path('reservas/', ReservasHomeView.as_view(), name='reservas-home'),
    path('reservas/dia/', SemanaSelectView.as_view(),
         name='reservas-reserva-dia'),
    path('reservas/dia/<int:year>/<int:month>/<int:day>',
         SemanaFechaSelectView.as_view(), name='reservas-reservas-dias'),
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>',
         FechaListView.as_view(),
         name='reserva-profesional-fecha-list'),
    #todo crear un buscador de fechas
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>/horario/'
         '<int:hour>', FechaHorarioListView.as_view(),
         name='reserva-profesional-fecha-hora-list'),
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>/horario_inicio/'
         '<int:hour_inicio>/<int:minute_inicio>/horario_fin/<int:hour_fin>/'
         '<int:minute_fin>/<int:profesional_pk>/<int:email_user_pk>',
         ReservaCreateView.as_view(),
         name='reservas-reserva-create'),
    path('reservas/dia/fecha/<int:year>/<int:month>/<int:day>/horario/'
         '<int:horario_hora>/<int:horario_minuto>/<int:profesional_pk>/buscador/',
         BuscadorEmailUserView.as_view(),
         name='reservas-emailuser-search'),
    path('reservas/buscador/reservas',
         BuscadorReservasView.as_view(),
         name='reservas-buscador-reservas'),
    path('reservas/confirmar/reserva/<int:pk>/',
         ConfirmacionReservaUpdateView.as_view(),
         name='reservas-confirmar-reserva'),
    path('reservas/cancelar/reserva/<int:pk>/',
         CancelacionReservaUpdateView.as_view(),
         name='reservas-cancelar-reserva'),
    path('reservas/resumen/reserva/<int:id_reserva>/',
         ResumenReservaView.as_view(), name='reservas-resumen-reserva'),
]

reservas/models.py
from customauth.models import EmailUser
from django.core.validators import MaxValueValidator
from django.db import models
from servicios.models import Profesional


class Reserva(models.Model):
    """
    Modelo que almacenara los detalles de una reserva

    :cvar fecha: DateField que almacena la fecha de reserva
    :cvar inicio_hora_reserva: TimeField que almacena la hora inicio de reserva
    :cvar fin_hora_reserva: TimeField que almacena la hora fin de reserva
    :cvar profesional: ForeignKey que almacena a que profesional pertenece la
        reserva
    :cvar email_user: ForeignKey que almacena el usuario que hizo la reserva
    :cvar precio_hora: FloatField que almacena el precio por hora
    :cvar precio_total: FloatField que almacena el total por todas las horas
    """
    RESERVADO = "1r"
    CONFIRMADO = "2c"
    CANCELADO = "3x"
    ESTADO_RESERVA = (
        (RESERVADO, "Reservado"),
        (CONFIRMADO, "Confirmado"),
        (CANCELADO, "Cancelado"),
    )
    fecha = models.DateField()
    inicio_hora_reserva = models.TimeField()
    fin_hora_reserva = models.TimeField()
    profesional = models.ForeignKey(
        Profesional, on_delete=models.CASCADE, null=True, related_name='reservas')
    email_user = models.ForeignKey(
        EmailUser, on_delete=models.CASCADE, null=True)
    precio_hora = models.FloatField()
    precio_total = models.FloatField()
    descuento = models.FloatField(default=0)
    #Todo: agregar validadores para que el precio > descuento y te muestre %
    estado = models.CharField(
        max_length=2, default=RESERVADO, choices=ESTADO_RESERVA)

    class Meta:
        verbose_name_plural = 'Reservas'
        verbose_name = 'Reserva'

    def __str__(self):
        return "{}, {}, {}".format(
            self.fecha, self.email_user.email, self.profesional.nombres)


class Resena(models.Model):
    """
    Modelo que almacena los datos de una reseña.

    :cvar reserva: ForeingKey OnoToOnoField que apunta a una Reserva.
    :cvar puntaje: PositiveIntegerField que guarda un puntaje.
    :cvar descripcion: TextField que guarda la descripcion de la reseña.
    """
    reserva = models.OneToOneField(
        Reserva, on_delete=models.CASCADE, related_name="reviews")
    puntaje = models.PositiveIntegerField(validators=[MaxValueValidator(5)])
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return "reserva: {} --> puntaje: {}".format(self.reserva.id, self.puntaje)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        profesional = self.reserva.profesional
        num_resenas = Resena.objects.filter(
            reserva__profesional=profesional).count()
        promedio = ((num_resenas * profesional.puntaje) + self.puntaje) / (
                num_resenas + 1)
        profesional.puntaje = promedio
        profesional.save()

        return super(Resena, self).save(
            force_insert=False, force_update=False, using=None,
            update_fields=None)


class TextModel(models.Model):
    """
    TextModel que contiene textos para la descripcion de protocolos, preguntas y
    respuestas

    :cvar texto: CharField que guarda la descripcion del objeto
    """

    texto = models.CharField(max_length=256)

    class Meta:
        abstract = True


class Protocolo(TextModel):
    """
    Modelo que guarda el protocolo del tipo de servicio

    :cvar tipo_servicio: ForeignKey para el tipo de servicio
    :cvar es_para_profesional: BooleanField queidentifica si es un protocolo
        para el profesional.
    """

    tipo_servicio = models.ForeignKey(
        'servicios.TipoServicio', on_delete=models.CASCADE)
    es_para_profesional = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'protocolo'
        verbose_name_plural = 'protocolos'

    def __str__(self):
        return f"{self.tipo_servicio}: {self.texto}"


class Pregunta(TextModel):
    """
    Modelo que guarda las preguntas del protocolo

    :cvar protocolo: ForeignKey que guarda a que protocolo al que pertenece
    :cvar question_type: CharField que guarda el tipo de pregunta que sera
    """

    QUESTION_TYPES = (
        ('R', 'Ranking'),
        ('B', 'Escala'),
        ('D', 'Dicotomicas(si,no)'),
    )
    protocolo = models.ForeignKey(Protocolo, on_delete=models.CASCADE)
    question_type = models.CharField(
        max_length=1, choices=QUESTION_TYPES, blank=True)

    class Meta:
        verbose_name = 'pregunta'
        verbose_name_plural = 'preguntas'

    def __str__(self):
        return f"{self.protocolo}: {self.texto}"

    def get_alternativas(self):
        """
        Metodo que obtiene las alternativas de esta pregunta.

        :return: PosibleRespuesta queryList.
        """
        alternativas = PosibleRespuesta.objects.filter(pregunta=self)
        return alternativas


class PosibleRespuesta(TextModel):
    """
    Modelo que guarda las posibles respuestas de preguntas

    :cvar pregunta: ForeignKey hacia el modelo pregunta
    :cvar weight: IntegerField que almacena el peso por si tienen que calcular
        el valor de las respuestas para sacar el puntaje del servicio
    """

    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    weight = models.IntegerField('peso', blank=True, null=True)

    class Meta:
        verbose_name = 'alternativa de respuesta'
        verbose_name_plural = 'alternativas de respuestas'

    def __str__(self):
        return f"{self.pregunta}: {self.texto}"


class Respuesta(models.Model):
    """
    Modelo que almacena la respuesta de los clientes

    :cvar reserva: ForeignKey hacia reserva
    :cvar respuesta_elegida: ForeignKey hacia la respuesta elegida
    """

    reserva = models.ForeignKey(Reserva, on_delete=models.CASCADE)
    respuesta_elegida = models.ForeignKey(
        PosibleRespuesta, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'respuesta'
        verbose_name_plural = 'respuestas'

    def __str__(self):
        return f"{self.respuesta_elegida}"

reservas/forms.py
from django import forms

from bootstrap_datepicker_plus import DateTimePickerInput


class FechaForm(forms.Form):
    """
    Form para la redireccion de fechas
    """
    fecha = forms.DateField(widget=DateTimePickerInput(format='%Y-%m-%d'))

reservas/templates/cancelacion_reserva.html
{% extends 'base.html' %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/servicios/cancha_list.css' %}">
{% endblock %}

{% block content %}

    <div class="d-flex justify-content-center">
        <div class="p-2">
            <div class="card" style="width: 100%;">
                <div class="card-body">
                    <h2 class="module-title"> Cancelando reserva: </h2>
                    <table class="table">
                        <thead>
                        <th>Fecha</th>
                        <th>Profesional</th>
                        <th>Horario</th>
                        <th>Precio</th>
                        </thead>
                        <tr>
                            <td>{{ reserva.fecha }}</td>
                            <td>{{ reserva.profesional.nombres }}</td>
                            <td>{{ reserva.inicio_hora_reserva }} - {{ reserva.fin_hora_reserva }}</td>
                            <td>{{ reserva.precio_total }}</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <a href="{% url 'reservas-buscador-reservas' %}" class="btn btn-danger">Cerrar</a>
                            </td>
                            <td colspan="2" align="right">
                                <form method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success">Cancelar</button>
                                </form>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

reservas/templates/confirmacion_reserva.html
{% extends 'base.html' %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/servicios/cancha_list.css' %}">
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
        <div class="p-2">
            <div class="card" style="width: 100%;">
                <div class="card-body">
                    <h2 class="module-title"> Confirmando reserva: </h2>
                    <table class="table">
                        <thead>
                        <th>Fecha</th>
                        <th>Profesional</th>
                        <th>Horario</th>
                        <th>Precio</th>
                        </thead>
                        <tr>
                            <td>{{ reserva.fecha }}</td>
                            <td>{{ reserva.profesional.nombres }}</td>
                            <td>{{ reserva.inicio_hora_reserva }} - {{ reserva.fin_hora_reserva }}</td>
                            <td>{{ reserva.precio_total }}</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <a href="{% url 'reservas-buscador-reservas' %}" class="btn btn-danger">Cerrar</a>
                            </td>
                            <td colspan="2" align="right">
                                <form method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success module-title">Confimar</button>
                                </form>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

reservas/templates/emailuser_search.html
{% extends 'base.html' %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/servicios/cancha_list.css' %}">
{% endblock %}

{% block content %}

    <div>
        <div>
            <div class="back-nav">
                <a style="float: left;" onClick="javascript:history.go(-1);"> <img alt="<-" src="{% static 'static/back_icon.svg' %}" width="40" height="40" class="centered-add-hover"> </a>
            </div>
            <h1 class="module-title">Buscador de Clientes</h1>
            <div class="d-flex justify-content-center">
                <div class="p-2">
                    <ul>
                        <li><h5>Profesional: {{ profesional.nombres|title }} {{ profesional.apellido_paterno|title }} {{ profesional.apellido_materno|title }}</h5></li>
                        <li><h5>Fecha: {{ fecha }}</h5></li>
                        <li><h5>Hora: {{ hour }}</h5></li>
                    </ul>
                </div>
            </div>
            <form action="{% url 'reservas-emailuser-search' fecha.year fecha.month fecha.day hour.hour hour.minute profesional.id %}" method="post">
                <div class="d-flex justify-content-center">
                    <div class="p-2">
                        {% csrf_token %}
                        <label for="query">Busque un cliente para la reserva</label>
                        <div class="input-group add-on">
                            <input class="form-control" placeholder="DNI, Correo Electrónico" name="query" value="{{ query }}" id="query" size="50">
                            <!-- Todo: si el performance se pone muy lento en esta parte, quitar busqueda por telefono -->
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"><img alt="<-" src="{% static 'static/search_icon.svg' %}" width="25" height="25"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            <div>
                {% if users %}
                    <h2 class="module-title"><b>Resultados</b></h2>
                    <table class="table table-sm" align="center" style="width: 70%;">
                        {% for user in users %}
                            <tr style="border-bottom: 2px solid black;">
                                <td class="align-middle module-title">
                                    <b>#{{ forloop.counter }}</b>
                                </td>
                                <td class="align-middle">
                                    <h4 class="list-group-item-text"><b>DNI: </b>{{ user.dni }}&emsp; <b>Email: </b>{{ user.email_user.email }}&emsp; <b>Telefono: </b>{{ user.telefono }}&emsp;</h4>
                                    <h5 class="list-group-item-text"><b>Nombre: </b>{{ user.nombres|title }} {{ user.apellido_paterno|title }} {{ user.apellido_materno|title }}</h5>
                                </td>
                                <td class="align-middle module-title">
                                    <a href="{% url 'reservas-reserva-create' fecha.year fecha.month fecha.day hour.hour hour.minute hora_fin.hour hora_fin.minute profesional.id user.email_user.id %}" class="btn btn-success">Crear</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

reservas/templates/reserva_fecha_hora_list.html
{% extends 'base.html' %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/servicios/cancha_list.css' %}">
{% endblock %}

{% block content %}
    <div class="back-nav">
        <a style="float: left;" onClick="javascript:history.go(-1);"> <img alt="<-" src="{% static 'static/back_icon.svg' %}" width="40" height="40" class="centered-add-hover"> </a>
    </div>
    <h1 class="module-title">Profesionales disponibles para el {{ date }}</h1>
    <h2 class="module-title">Hora: {{ page_context.hour }}:00</h2>
    <div class="previous-next-div">
        <div style='float: left;'>
            <a href="{% url 'reserva-profesional-fecha-hora-list' page_context.year page_context.month page_context.day page_context.hour %}" class="btn-editar btn btn-info">Una hora menos</a>
        </div>
        <div style='float: right'>
            <a href="{% url 'reserva-profesional-fecha-hora-list' page_context.year page_context.month page_context.day page_context.hour %}" class="btn-editar btn btn-info">Una hora mas</a>
        </div>
    </div>
    <h2 class="module-title">Profesionales Disponibles</h2>
    <div class="panel-group">
        <table class="table">
            <tr>
                <th>Nombre del profesional</th>
                <th>Precio</th>
                <th>Acción</th>
            </tr>
            {% for profesional in profesionales %}
                <tr>
                    <td><b>{{ profesional.nombres }}</b></td>
                    <td>S/. {{ profesional.precio }}</td>
                    <td><a class="btn btn-primary" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">Mostrar horarios</a></td>
                </tr>
                <tr>
                    <td colspan="3">
                        <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
                            <table class="table">
                                {% for minutos in profesional.intervalos_minutos %}
                                    <tr>
                                        <td>{{ page_context.hour }}:{{ minutos }}</td>
                                        <td><a class="btn btn-primary" href="{% url 'reservas-emailuser-search' page_context.year page_context.month page_context.day page_context.hour minutos profesional.id %}">Seleccionar horario</a></td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

reservas/templates/reserva_fecha_list.html
{% extends 'base.html' %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/servicios/cancha_list.css' %}">
{% endblock %}

{% block content %}
    <div class="back-nav">
        <a style="float: left;" onClick="javascript:history.go(-1);"> <img alt="<-" src="{% static 'static/back_icon.svg' %}" width="40" height="40" class="centered-add-hover"> </a>
    </div>
    <h1 class="module-title">Horario por Fecha</h1>
    <h3 class="module-title">{{ page_context }}</h3>
    <div class="previous-next-div">
        {% if today < page_context %}
            <div style='float: left;'>
                <a href="{% url 'reserva-profesional-fecha-list' yesterday.year yesterday.month yesterday.day %}" class="btn-editar btn btn-info">
                    Ayer
                    <br>
                    {{ yesterday }}
                </a>
            </div>
        {% endif %}
        <div style='float: right;'>
            <a href="{% url 'reserva-profesional-fecha-list' tomorrow.year tomorrow.month tomorrow.day %}" class="btn-editar btn btn-info">
                Mañana
                <br>
                {{ tomorrow }}
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped table-sm" align="center" style="width: 35%" >
        <thead class="thead-dark-theme">
        <tr>
            <th class="module-title">Hora inicio</th>
            <th class="module-title">Profesionales disponibles</th>
        </tr>
        </thead>
        <tbody>
        {% for hora in horas %}
            <tr>
                <td align="center">{{ hora.inicio }}:00</td>
                <td align="center"><a href="{% url 'reserva-profesional-fecha-hora-list' page_context.year page_context.month page_context.day hora.inicio %}">{{ hora.profesionales_disponibles }} Profesionales</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

reservas/templates/reserva_search.html
{% extends 'base.html' %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/servicios/cancha_list.css' %}">
    <link rel="stylesheet" href="{% static 'css/reservas/reserva_search.css' %}">
{% endblock %}

{% block content %}
    <div class="back-nav">
        <a style="float: left;" onClick="javascript:history.go(-1);"> <img alt="<-" src="{% static 'static/back_icon.svg' %}" width="40" height="40" class="centered-add-hover"> </a>
    </div>
    <h1 class="module-title">Buscador de Reservas</h1>
    <form action="{% url 'reservas-buscador-reservas' %}" method="post">
        <div class="d-flex justify-content-center">
            <div class="p-2">
                {% csrf_token %}
                <div class="input-group add-on">
                    <input class="form-control" placeholder="Id o Correo Electrónico" name="query" value="{{ query }}" id="query" size="50">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"><img alt="<-" src="{% static 'static/search_icon.svg' %}" width="25" height="25"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% if reservas %}
        <h2 class="module-title"><b>Resultados</b></h2>
        <table class="table table-sm" align="center" style="width: 70%;">
            {% for reserva in reservas %}
                <tr style="border-bottom: 2px solid black;">
                    <td class="align-middle module-title ">
                        <b>#{{ forloop.counter }}</b>
                    </td>
                    </td>
                    <td>
                        <h3><b>Nro: {{ reserva.id }} <b>Estado:</b> {{ reserva.get_estado_display }}</b></h3>
                        {{ reserva.fecha }} - {{ reserva.profesional.nombres|title }}
                        <br>
                        <p>{{ reserva.inicio_hora_reserva }} - {{ reserva.fin_hora_reserva }} &emsp; S/. {{ reserva.precio_total }}</p>
                    </td>
                    <td class="align-middle module-title">
                        <div class="btn-group" role="group" aria-label="Basic example">
                        {% if reserva.estado == '1r' %}
                            <a href="{% url 'reservas-confirmar-reserva' reserva.id %}" class="btn btn-success">
                                Confirmar
                                <br>
                                Reserva
                            </a>
                        {% endif %}
                        {% if reserva.estado == '1r' %}
                            <a href="{% url 'reservas-cancelar-reserva' reserva.id %}" class="btn btn-danger">
                                Cancelar
                                <br>
                                Reserva
                            </a>
                        {% endif  %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

reservas/templates/resumen_reserva.html
{% extends 'base.html' %}
{% load static %}
{% load poll_extras %}
{% block content %}
    <div class="back-nav">
        <a style="float: left;" onClick="javascript:history.go(-1);"> <img alt="<-" src="{% static 'static/back_icon.svg' %}" width="40" height="40" class="centered-add-hover"> </a>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header text-center">
                    <h3 class="card-title"><b>Detalle de reserva Nro: {{ reserva.id }}</b></h3>
                </div>
                <div class="card-body" style="padding: 0px;">
                    <div class="row text-center">
                        <div class="col-lg-6">
                            <h5 class="card-text"><b>Para la fecha: </b>{{ reserva.fecha }}</h5>
                            <h5 class="card-text"><b>Desde: </b>{{ reserva.inicio_hora_reserva }}, <b>hasta: </b>{{ reserva.fin_hora_reserva }}</h5>
                            <h5 class="card-text"><b>Profesional: </b>{{ reserva.profesional.nombres }} {{ reserva.profesional.apellido_paterno }} {{ reserva.profesional.apellido_materno }}</h5>
                            {% if reserva.descuento == 0 %}
                                <h5 class="card-text"><b>Sin descuento</b></h5>
                            {% else %}
                                <h5 class="card-text"><b>Descuento: </b>{{ reserva.descuento }}</h5>
                            {% endif %}
                        </div>
                        <div class="col-lg-6">
                            <h5 class="card-text"><b>Para el usuario: </b>{{ reserva.email_user.email }}</h5>
                            <h5 class="card-text"><b>Precio Total: </b>{{ reserva.precio_total }}</h5>
                            <h5 class="card-text"><b>Precio por hora: </b>{{ reserva.precio_hora }}</h5>
                            <h5 class="card-text"><b>Estado: </b>{{ reserva.get_estado_display }}</h5>
                        </div>
                    </div>
                </div>
                <div class="card-header">
                    <table style="width: 100%">
                        <tr>
                            <td class="text-center" style="width: 50%;"><h4><b>Pregunta respecto al Profesional</b></h4></td>
                            <td class="text-center" style="width: 50%;"><h4><b>Alternativas</b></h4></td>
                        </tr>
                    </table>
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="card-body" style="padding: 0px;">
                        <table style="width: 100%;">
                            {% for pregunta in preguntas %}
                                <tr>
                                    <td class="text-center"><p>{{ pregunta.texto }}</p></td>
                                    <td class="text-center">
                                        {% if pregunta.get_alternativas %}
                                            {% for alternativa in pregunta.get_alternativas %}
                                                {% get_respuesta alternativa.id reserva.id as respuesta %}
                                                {% if respuesta %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="{{ pregunta.id }}" id="{{alternativa.id}}" value="{{ alternativa.id }}" checked>
                                                        <label class="form-check-label" for="{{alternativa.id}}">{{alternativa.texto}}</label>
                                                    </div>
                                                {% else %}
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="{{ pregunta.id }}" id="{{alternativa.id}}" value="{{ alternativa.id }}">
                                                        <label class="form-check-label" for="{{alternativa.id}}">{{alternativa.texto}}</label>
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <div class="card-footer">
                        <table style="width: 100%">
                            <tr>
                                <td style="width: 100%" class="text-left"><a href="{% url 'reservas-home' %}" class="card-link btn-primary btn">Salir</a></td>
                                <td style="width: 100%" class="text-right"><button class="btn-primary btn" type="submit">Enviar Respuestas</button></td>
                            </tr>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}